// AUTO-GENERATED by `python3 -m spuc.isa --sv` -- do not edit by hand.
package spu_pkg;
  // ---- configuration ----
  localparam int D          = 8192;
  localparam int W          = 512;
  localparam int NHREG      = 32;
  localparam int NSREG      = 32;
  localparam int NACC       = 16;
  localparam int ACC_LANES  = 128;
  localparam int ACC_BITS   = 16;
  localparam int PROG_DEPTH = 4096;
  localparam int C          = D / W;          // chunks per hypervector
  localparam int HV_BYTES   = D / 8;
  localparam int ACC_STEPS  = D / ACC_LANES;
  localparam int CH_W       = $clog2(C);      // chunk index width
  localparam int RF_AW      = $clog2(NHREG) + CH_W;
  localparam int ACC_SPC    = W / ACC_LANES;  // accumulator steps per chunk
  localparam int ACC_BEATS  = D * ACC_BITS / W; // 64B beats in an accumulator image
  localparam int STEP_W     = $clog2(ACC_STEPS); // accumulator step index width
  localparam int HOST_AW    = 18;
  localparam logic [31:0] SPU_ID      = 32'h53505531;
  localparam logic [31:0] SPU_VERSION = 32'h00010000;
  // ---- opcodes ----
  localparam logic [5:0] OP_NOP      = 6'h00;
  localparam logic [5:0] OP_HALT     = 6'h01;
  localparam logic [5:0] OP_SOP      = 6'h02;
  localparam logic [5:0] OP_SOPI     = 6'h03;
  localparam logic [5:0] OP_LW       = 6'h04;
  localparam logic [5:0] OP_LB       = 6'h05;
  localparam logic [5:0] OP_SW       = 6'h06;
  localparam logic [5:0] OP_SB       = 6'h07;
  localparam logic [5:0] OP_BR       = 6'h08;
  localparam logic [5:0] OP_JAL      = 6'h09;
  localparam logic [5:0] OP_JALR     = 6'h0A;
  localparam logic [5:0] OP_CSRR     = 6'h0B;
  localparam logic [5:0] OP_CSRW     = 6'h0C;
  localparam logic [5:0] OP_HXOR     = 6'h10;
  localparam logic [5:0] OP_HAND     = 6'h11;
  localparam logic [5:0] OP_HOR      = 6'h12;
  localparam logic [5:0] OP_HNOT     = 6'h13;
  localparam logic [5:0] OP_HROT     = 6'h14;
  localparam logic [5:0] OP_HGEN     = 6'h15;
  localparam logic [5:0] OP_HMASK    = 6'h16;
  localparam logic [5:0] OP_HLD      = 6'h18;
  localparam logic [5:0] OP_HST      = 6'h19;
  localparam logic [5:0] OP_HDIST    = 6'h1A;
  localparam logic [5:0] OP_HSEARCH  = 6'h1B;
  localparam logic [5:0] OP_HACC     = 6'h1C;
  // ---- scalar ALU functions ----
  localparam logic [5:0] ALU_ADD   = 6'd0;
  localparam logic [5:0] ALU_SUB   = 6'd1;
  localparam logic [5:0] ALU_AND   = 6'd2;
  localparam logic [5:0] ALU_OR    = 6'd3;
  localparam logic [5:0] ALU_XOR   = 6'd4;
  localparam logic [5:0] ALU_SHL   = 6'd5;
  localparam logic [5:0] ALU_SHR   = 6'd6;
  localparam logic [5:0] ALU_SRA   = 6'd7;
  localparam logic [5:0] ALU_MUL   = 6'd8;
  localparam logic [5:0] ALU_SLT   = 6'd9;
  localparam logic [5:0] ALU_SLTU  = 6'd10;
  // ---- branch conditions ----
  localparam logic [5:0] BR_BEQ   = 6'd0;
  localparam logic [5:0] BR_BNE   = 6'd1;
  localparam logic [5:0] BR_BLT   = 6'd2;
  localparam logic [5:0] BR_BGE   = 6'd3;
  localparam logic [5:0] BR_BLTU  = 6'd4;
  localparam logic [5:0] BR_BGEU  = 6'd5;
  // ---- search flags ----
  localparam int SEARCH_WRDIST_BIT = 0;
  // ---- accumulator functions ----
  localparam logic [5:0] ACC_CLR  = 6'd0;
  localparam logic [5:0] ACC_ADD  = 6'd1;
  localparam logic [5:0] ACC_SUB  = 6'd2;
  localparam logic [5:0] ACC_THR  = 6'd3;
  localparam logic [5:0] ACC_LD   = 6'd4;
  localparam logic [5:0] ACC_ST   = 6'd5;
  // ---- CSR indices ----
  localparam int CSR_ID          = 0;
  localparam int CSR_DOUT        = 1;
  localparam int CSR_SR_IDX      = 2;
  localparam int CSR_SR_DIST     = 3;
  localparam int CSR_SR_IDX2     = 4;
  localparam int CSR_SR_DIST2    = 5;
  localparam int CSR_CYCLES_LO   = 6;
  localparam int CSR_CYCLES_HI   = 7;
  localparam int CSR_INSTRET_LO  = 8;
  localparam int CSR_INSTRET_HI  = 9;
  localparam int CSR_CFG_D       = 10;
  localparam int CSR_CFG_NACC    = 11;
  localparam int CSR_ERR         = 12;
  localparam int CSR_SCRATCH0    = 13;
  localparam int CSR_SCRATCH1    = 14;
  localparam int CSR_SCRATCH2    = 15;
  localparam int CSR_SCRATCH3    = 16;
  localparam int NCSR = 32;
  // ---- error codes ----
  localparam logic [7:0] ERR_NONE        = 8'd0;
  localparam logic [7:0] ERR_ILLEGAL_OP  = 8'd1;
  localparam logic [7:0] ERR_ACC_INDEX   = 8'd2;
  localparam logic [7:0] ERR_PC_RANGE    = 8'd3;
  localparam logic [7:0] ERR_AXI         = 8'd4;
  // ---- host register map (byte offsets) ----
  localparam logic [HOST_AW-1:0] HOST_CTRL         = 'h00000;
  localparam logic [HOST_AW-1:0] HOST_STATUS       = 'h00004;
  localparam logic [HOST_AW-1:0] HOST_PC_START     = 'h00008;
  localparam logic [HOST_AW-1:0] HOST_PC           = 'h0000C;
  localparam logic [HOST_AW-1:0] HOST_MEM_BASE_LO  = 'h00010;
  localparam logic [HOST_AW-1:0] HOST_MEM_BASE_HI  = 'h00014;
  localparam logic [HOST_AW-1:0] HOST_IRQ_ACK      = 'h00018;
  localparam logic [HOST_AW-1:0] HOST_ID           = 'h00020;
  localparam logic [HOST_AW-1:0] HOST_VERSION      = 'h00024;
  localparam logic [HOST_AW-1:0] HOST_CFG0         = 'h00028;
  localparam logic [HOST_AW-1:0] HOST_CFG1         = 'h0002C;
  localparam logic [HOST_AW-1:0] HOST_CSR_BASE     = 'h00100;
  localparam logic [HOST_AW-1:0] HOST_SREG_BASE    = 'h00200;
  localparam logic [HOST_AW-1:0] HOST_HREG_BASE    = 'h00400;
  localparam logic [HOST_AW-1:0] HOST_PROG_BASE    = 'h20000;
  localparam int CTRL_START_BIT = 0, CTRL_SOFT_RESET_BIT = 1, CTRL_IRQ_EN_BIT = 2;
  localparam int STATUS_BUSY_BIT = 0, STATUS_DONE_BIT = 1, STATUS_ERR_BIT = 2, STATUS_IRQ_BIT = 3;
  // ---- instruction word ----
  typedef struct packed {
    logic [5:0]  op;
    logic [5:0]  fn;
    logic [4:0]  rd;
    logic [4:0]  ra;
    logic [4:0]  rb;
    logic [4:0]  rc;
    logic [31:0] imm;
  } instr_t;
  // ---- pseudo random generator constants (splitmix64 finaliser) ----
  localparam logic [63:0] GEN_GOLDEN = 64'h9E3779B97F4A7C15;
  localparam logic [63:0] GEN_MUL1   = 64'hBF58476D1CE4E5B9;
  localparam logic [63:0] GEN_MUL2   = 64'h94D049BB133111EB;
endpackage
