/* AUTO-GENERATED by scripts/gen_headers.py from sw/spuc/isa.py */
#ifndef SPU_REGS_H
#define SPU_REGS_H

#define SPU_HOST_CTRL           0x00000
#define SPU_HOST_STATUS         0x00004
#define SPU_HOST_PC_START       0x00008
#define SPU_HOST_PC             0x0000C
#define SPU_HOST_MEM_BASE_LO    0x00010
#define SPU_HOST_MEM_BASE_HI    0x00014
#define SPU_HOST_IRQ_ACK        0x00018
#define SPU_HOST_ID             0x00020
#define SPU_HOST_VERSION        0x00024
#define SPU_HOST_CFG0           0x00028
#define SPU_HOST_CFG1           0x0002C
#define SPU_HOST_CSR_BASE       0x00100
#define SPU_HOST_SREG_BASE      0x00200
#define SPU_HOST_HREG_BASE      0x00400
#define SPU_HOST_PROG_BASE      0x20000

#define SPU_CSR_ID             0
#define SPU_CSR_DOUT           1
#define SPU_CSR_SR_IDX         2
#define SPU_CSR_SR_DIST        3
#define SPU_CSR_SR_IDX2        4
#define SPU_CSR_SR_DIST2       5
#define SPU_CSR_CYCLES_LO      6
#define SPU_CSR_CYCLES_HI      7
#define SPU_CSR_INSTRET_LO     8
#define SPU_CSR_INSTRET_HI     9
#define SPU_CSR_CFG_D          10
#define SPU_CSR_CFG_NACC       11
#define SPU_CSR_ERR            12
#define SPU_CSR_SCRATCH0       13
#define SPU_CSR_SCRATCH1       14
#define SPU_CSR_SCRATCH2       15
#define SPU_CSR_SCRATCH3       16

#define SPU_CTRL_START      0x1
#define SPU_CTRL_SOFT_RESET 0x2
#define SPU_CTRL_IRQ_EN     0x4
#define SPU_STATUS_BUSY     0x1
#define SPU_STATUS_DONE     0x2
#define SPU_STATUS_ERR      0x4
#define SPU_ID_VALUE        0x53505531U
#define SPU_D               8192
#define SPU_HV_BYTES        1024

#endif
