#!/usr/bin/env python3
"""Regenerate hw/rtl/spu_pkg.sv and hw/host/spu_regs.h from sw/spuc/isa.py."""
import os, sys
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, os.path.join(root, "sw"))
from spuc import isa

with open(os.path.join(root, "hw/rtl/spu_pkg.sv"), "w") as f:
    f.write(isa.emit_sv_package())

L = ["/* AUTO-GENERATED by scripts/gen_headers.py from sw/spuc/isa.py */", "#ifndef SPU_REGS_H", "#define SPU_REGS_H", ""]
for k, v in isa.HOST.items():
    L.append("#define SPU_HOST_%-14s 0x%05X" % (k, v))
L.append("")
for k, v in isa.CSR.items():
    L.append("#define SPU_CSR_%-14s %d" % (k, v))
L += ["", "#define SPU_CTRL_START      0x1", "#define SPU_CTRL_SOFT_RESET 0x2", "#define SPU_CTRL_IRQ_EN     0x4",
      "#define SPU_STATUS_BUSY     0x1", "#define SPU_STATUS_DONE     0x2", "#define SPU_STATUS_ERR      0x4",
      "#define SPU_ID_VALUE        0x%08XU" % isa.SPU_ID, "#define SPU_D               %d" % isa.DEFAULT_CONFIG.D,
      "#define SPU_HV_BYTES        %d" % isa.DEFAULT_CONFIG.HV_BYTES, "", "#endif"]
with open(os.path.join(root, "hw/host/spu_regs.h"), "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote hw/rtl/spu_pkg.sv and hw/host/spu_regs.h")
